from typing import Protocol

class UserProtocol(Protocol):
    async def delete_product(self, tg_id: str, product_url: str) -> bool:
        ...
    async def add_product(self, tg_id: str, product_url: str) -> bool:
        ...
    async def get_tracking_list(self, tg_id: str) -> list[str]:
        ...
    async def is_user_exist(self, tg_id: str) -> bool:
        ...
    async def create_if_not_exists(self, tg_id: str) -> None:
        ...